version: '3.9'

volumes:
  app:
  database:

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: "web_scrapper"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  bot:
    image: danielshtel/bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    command: bash -c "python bot.py"
    ports:
      - "80:80"
  web-scrapper:
    image: danielshtel/web-scrapper
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "python database.py && python scrapper.py"
    env_file:
      - .env
    volumes:
      - app:/web-scrapper
    depends_on:
      - bot

