version: '3.9'

volumes:
  data:
  database:

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: "web_scrapper"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - database:/postgresql/data
    ports:
      - "5435:5432"



  web-scrapper:
    image: danielshtel/web-scrapper
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "python database.py && python scrapper.py"
    volumes:
      - data:/web-scrapper
    depends_on:
      - database

